Da <- c(5,25,13,10,20)
 barplot(Da)
 ma <- c("Jan","Feb","Mar","Apr","May")
 barplot(Da,names.arg=ma,xlab="Mo",ylab="rev")
 barplot(Da,names.arg=ma,xlab="Mo",ylab="rev",border="green")
 barplot(Da,names.arg=ma,xlab="Mo",ylab="rev",border="green",col="red")